import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: "black",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "start",
          flexDirection: "column",
          minHeight: "100vh",
          margin: "auto",
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
